# Generated by Django 3.1.1 on 2020-09-21 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('media', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='WelcomeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='tmessages.message')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_message', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='tmessages.message')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirm_message', to='projects.project')),
            ],
        ),
    ]
