# Generated by Django 3.1.1 on 2020-09-17 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tmessages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=200)),
                ('confirm_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirm_message', to='tmessages.message')),
                ('welcome_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_message', to='tmessages.message')),
            ],
        ),
    ]
