# Generated by Django 3.1.1 on 2020-09-17 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tmessages', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='confirm_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='confirm_message', to='tmessages.message'),
        ),
        migrations.AlterField(
            model_name='project',
            name='welcome_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='welcome_message', to='tmessages.message'),
        ),
    ]
