# Generated by Django 3.1.1 on 2020-09-17 18:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(unique=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Deleted')], default=1)),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(
                    message="Phone number must be entered in the format: '77077070077'. Up to 11 digits allowed.",
                    regex='^(7)([0-9]{10})$')])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients',
                                              to='projects.project')),
            ],
        ),
    ]
