# Generated by Django 3.1.1 on 2020-09-18 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0002_hour'),
        ('projects', '0002_auto_20200918_0059'),
        ('tmessages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('day', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'Active'), (3, 'Deleted')], default=1)),
                ('hour', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.hour')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tmessages.message')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_lessons',
                                              to='projects.project')),
            ],
            options={
                'db_table': 'daily_lessons_daily_lesson',
            },
        ),
    ]
