# Generated by Django 3.1.1 on 2020-09-17 18:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tmessages', '0001_initial'),
        ('lessons', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 9, 17, 18, 44, 3, 783272, tzinfo=utc))),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'Active'), (3, 'Sent')], default=1)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timed_messages', to='lessons.lesson')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tmessages.message')),
                ('timing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.timing')),
            ],
            options={
                'db_table': 'messages_timed_message',
            },
        ),
    ]
