# Generated by Django 3.1.1 on 2020-09-21 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        ('daily_lessons', '0001_initial'),
        ('core', '0001_initial'),
        ('tmessages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTimedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'Active'), (3, 'Sent')], default=1)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timed_messages', to='lessons.lesson')),
                ('message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_timed', to='tmessages.message')),
                ('timing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.timing')),
            ],
            options={
                'db_table': 'timed_messages_lesson_timed_message',
            },
        ),
        migrations.CreateModel(
            name='DailyLessonTimedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Created'), (2, 'Active'), (3, 'Sent')], default=1)),
                ('daily_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timed_messages', to='daily_lessons.dailylesson')),
                ('message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_lesson_timed', to='tmessages.message')),
                ('timing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.timing')),
            ],
            options={
                'db_table': 'timed_messages_daily_lesson_timed_message',
            },
        ),
    ]
