# Generated by Django 3.1.1 on 2020-09-21 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmessages', '0002_auto_20200921_1150'),
        ('timed_messages', '0002_auto_20200921_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylessontimedmessage',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_lesson_timed', to='tmessages.message'),
        ),
        migrations.AlterField(
            model_name='lessontimedmessage',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_timed', to='tmessages.message'),
        ),
    ]
