# Generated by Django 3.1.1 on 2020-09-19 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20200919_1612'),
        ('daily_lessons', '0001_initial'),
        ('timed_messages', '0004_auto_20200918_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedmessage',
            name='daily_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timed_messages', to='daily_lessons.dailylesson'),
        ),
        migrations.AlterField(
            model_name='timedmessage',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timed_messages', to='lessons.lesson'),
        ),
    ]
