# Generated by Django 3.1.1 on 2020-09-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instant_messages', '0002_auto_20200921_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instantmessage',
            name='date',
            field=models.DateTimeField(default='2020-09-21 13:14'),
        ),
    ]
