# Generated by Django 3.1.1 on 2020-09-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instant_messages', '0003_auto_20200918_0056'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='instantmessage',
            table='instant_messages_instant_message',
        ),
    ]
