# Generated by Django 3.1.1 on 2020-09-18 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200918_0059'),
        ('instant_messages', '0004_auto_20200918_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instantmessage',
            name='lesson',
        ),
        migrations.AddField(
            model_name='instantmessage',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='instant_messages', to='projects.project'),
            preserve_default=False,
        ),
    ]
